# Classification of Induction Motor Faults

In [5]:
import numpy as np
from scipy.io import loadmat

data = loadmat('C:\\Users\\Hp Probook\\Desktop\\5th_sem\\EM\\sem proj\\IMFaults_dataset_min.mat')

X = data['X']          # (n_samples, 10)
y = data['y'].ravel()  # make it 1D
print(X.shape, y.shape, np.unique(y, return_counts=True))


(39500, 10) (39500,) (array([0, 1, 2, 3], dtype=uint8), array([15800,  7900,  7900,  7900], dtype=int64))


## Splitting data for train and test

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 20% test set
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0, stratify=y
)

# Standardize features (mean 0, std 1)
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std  = scaler.transform(X_test)


## Random Forest Classifier

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    random_state=0,
    n_jobs=-1
)

rf.fit(X_train_std, y_train)

y_pred = rf.predict(X_test_std)

print("Test accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification report:\n", classification_report(y_test, y_pred))
print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))


Test accuracy: 0.9931645569620253

Classification report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      3160
           1       1.00      1.00      1.00      1580
           2       0.99      0.99      0.99      1580
           3       1.00      0.98      0.99      1580

    accuracy                           0.99      7900
   macro avg       0.99      0.99      0.99      7900
weighted avg       0.99      0.99      0.99      7900


Confusion matrix:
 [[3150    0    6    4]
 [   0 1580    0    0]
 [  15    0 1564    1]
 [  25    0    3 1552]]


In [17]:
## Saving model for later use

import joblib
joblib.dump(rf, 'rf_im_faults.pkl')
joblib.dump(scaler, 'scaler_im_faults.pkl')

['scaler_im_faults.pkl']